### ISSUE TITLE
Integrate with sbom-action (and other) SBOM artifacts for scanning

### ISSUE THREAD

**Issue by kzantow** [anchore/scan-action#123]
The [sbom-action](github.com/anchore/sbom-action) can generate SBOMs at multiple steps during a project lifecycle, this vulnerability scan action should be able to use those SBOMs, for example during a nightly vulnerability scan to determine if something that may not have had vulnerabilities at the time it was built now has some identified.

Generally speaking, we need to be able to:
* Run `sbom-action` to generate an SBOM
* Continually run `scan-action` on the same SBOM to identify newly reported vulnerabilities

There is [a PR to add an `sbom` parameter](https://github.com/anchore/scan-action/pull/154), which would actually work well to provide this functionality.

- [ ] NOTE: after this has been implemented in a meaningful manner, follow up with: https://github.com/anchore/sbom-action/issues/157

**Comment by harmw** [comment]
I've been playing a little in https://github.com/harmw/scan-action/pull/1 to get `grype` to just read arbitrary sources, as my use-case is simply to go and read `sbom:file` generating from a previous `syft` task.

Apparently the `dist/index.js` file is going from 5332 lines to 345 after I run `npm run build` so I'm a little reluctant to commit that one (making online testing impossible) - what am I missing here 😂

**Comment by kzantow** [comment]
Hi @harmw this particular issue probably isn't the best to discuss a separate problem -- you could drop in the community slack or open another issue perhaps? I'll say that you _definitely_ need the `dist/index.js` to be checked in -- that's what the action actually runs: a compiled version of the `index.js`, including dependencies. You _should_ just be able to `npm install`, and then it _should_ just automatically get generated when you `git commit` due to a precommit hook that gets installed but I see in your branch it isn't committed at all. Puzzling. Did you run `npm install`? Maybe if you commit the `dist/index.js` I could look and see what the differences are and it would shed some light on what is going on.

**Comment by harmw** [comment]
Oh yeah, sorry - absolutely, and probably not running `npm install` will be part of the problem 🤦 (was aiming to have actions do all that stuff)

Anyway, I'll get it checked in and report back either here or in a PR 👍
