### ISSUE TITLE
Action fails but no report uploaded

### ISSUE THREAD

**Issue by Glennmen** [anchore/scan-action#130]
I want to add this workflow to my project, currently it fails but no report is uploaded.
Also I couldn't find any information in the README what to add to still receive the report because currently I have no idea why it failed.

The PR with failing action: https://github.com/Glennmen/datadog-event-action/pull/7

Any advice is appreciated.

**Comment by luhring** [comment]
Yeah, this is not a good experience. Sorry about this. Let me look into it...

**Comment by luhring** [comment]
As a starting point, check out the [Action Inputs](https://github.com/anchore/scan-action#action-inputs) section in the README. You should be able to temporarily work around this by setting `fail-build` to `false` _(it defaults to `true`)_, especially as you're still working on adding this checkpoint in your pipeline.

Another setting that could help us troubleshoot this is to set `debug` to `true` _(it defaults to `false`)_. This should add more details entries to the action logs.

**Comment by luhring** [comment]
I just noticed #128 — would you want to try the approach described there? Admittedly this is a non-obvious solution, and we need a better user experience here.

**Comment by Glennmen** [comment]
Thanks! I was able to get the report by using `continue-on-error: true`.
For me this ticket can be closed.

**Comment by luhring** [comment]
Sounds good! Thanks @Glennmen
