### ISSUE TITLE
Action : Secret scanning Documentation

### ISSUE THREAD

**Issue by sharmmoh1983** [anchore/scan-action#131]
Hi Team

Does this action covers following points:

Secret scanning in images
Vulnerabilities  scanning
Compliance scanning

**Comment by luhring** [comment]
Hi @sharmmoh1983 — this action does **vulnerability scanning** (for repositories and container images), using [Grype](https://github.com/anchore/grype).

**Comment by spiffcs** [comment]
@luhring I'm going to close this issue since the question has been answered. If you think we should update the docs in any way here I can also do that, but after giving them an initial read the first sentences are pretty clear on what it's doing.
