### ISSUE TITLE
Integration of only-fixed function in the action

### ISSUE THREAD

**Issue by lucapisciotta** [anchore/scan-action#133]
Actually seems that there isn't a way to use `--only-fixed` functionality that is integrated on official grype release but, I thinks is really useful because for me is useless have a notification, maybe with a medium or higher security level that i can't fix because it doesn't exist a fixed package.
I tried to integrate directly grype commands on my workflow but it have no possibility to create acs report.
Have you any suggestions?

**Comment by luhring** [comment]
@lucapisciotta This is a great point! We should do that. I could see this being available as an input to the action (under the `with` block).

We also have a loosely related issue #132, which would provide an alternative method of ignoring matches of vulnerabilities that aren't fixed.

**Comment by lucapisciotta** [comment]
Sure, it should be a solution 😊

**Comment by lucacome** [comment]
I'd love to see an input for the `--only-fixed` flag as it's the most relevant info imho

**Comment by spliskamatyshak-w3** [comment]
This --only-fixed flag feature really needs some traction, especially when dealing with python and all the ancient versions that are still installed on linux.
