### ISSUE TITLE
Action is not available as an example workflow

### ISSUE THREAD

**Issue by alfredodeza** [anchore/scan-action#143]
Hi!

Working on some demos today I found out that this action doesn't show up as a sample workflow in a GitHub project 😢  

Having it as a sample workflow is great because:

* Creates visibility
* Makes it easy to "install" the action in a project

It was super surprising to see some other company (!) provide an action that uses _scan-action_ itself for scanning 

![Screen Shot 2022-03-07 at 2 11 34 PM](https://user-images.githubusercontent.com/317847/157101752-7f42f71e-f961-48b7-bd75-ddd4e34bc145.png)

**Comment by alfredodeza** [comment]
Some extra context... the action does look like it is in the marketplace, it just doesn't show as a _workflow_. This is super odd :/ Not sure what extra steps are needed here to show up right in that menu where you can add workflows on the fly

**Comment by luhring** [comment]
Thanks @alfredodeza! @kzantow can you look into this when you get a chance?

**Comment by spiffcs** [comment]
https://github.com/actions/starter-workflows/pull/1630 <-- this has been added as a PR for scan action to be added as a starter workflow

**Comment by adriens** [comment]
@alfredodeza , hopefully [this short DEV.to](https://dev.to/optnc/docker-image-security-scan-automation-with-gh-issues-2h0p) post could help you.

**Comment by kzantow** [comment]
The workflow referenced here actually is a `scan-action` workflow, however, it was one of the first GitHub actions and as such has an incorrect author for reasons unknown. I've submitted an updated workflow here: https://github.com/actions/starter-workflows/pull/1697

**Comment by kzantow** [comment]
This has been merged! https://github.com/anchore/scan-action/actions/new?category=none&query=anchore
