### ISSUE TITLE
Get scan detail in an output variable

### ISSUE THREAD

**Issue by mbarre** [anchore/scan-action#169]
Hi,

In our workflows, we scan the image, make the workflow fails and generate an issue. It would be very useful if we can get the detail of the analysis in an output variable that we can inject in the issue we just made. 

What do you think about it ?

Thanks.

**Comment by adriens** [comment]
Looks a bit like https://github.com/anchore/scan-action/issues/168

**Comment by adriens** [comment]
May also be related to https://github.com/anchore/scan-action/issues/162

**Comment by adriens** [comment]
Also @mbarre https://github.com/anchore/scan-action/issues/128

**Comment by tgerla** [comment]
I'm going to close this since it is a near-duplicate of #162. Please head over there if you are interested in this feature.
