### ISSUE TITLE
Failed to fetch locally built image

### ISSUE THREAD

**Issue by razor54** [anchore/scan-action#171]
Hi there, I have been using scan-action for a couple of months, but today I got an issue where locally built images aren't being correctly fetched. it seems it's trying to connect to docker hub, and fails because I haven't used any authentication.
I confirmed that the local image has the correct tag.
To note that this was working before, the exact same workflow, but today I noticed it wasn't working anymore, I can't state the exact date it stopped working becuase I havent been using this on a daily basis
![Screenshot 2022-04-26 at 16 27 01](https://user-images.githubusercontent.com/25188139/165337560-96953edc-e9a5-4bf4-a54f-0481bdc56a57.png)
.

**Comment by joshbressers** [comment]
I'm going to close this as stale. If this is still a problem please reopen the issue and it would be appreciated if you could provide instructions for reproducing the problem.
