### ISSUE TITLE
.grype.yaml ignored

### ISSUE THREAD

**Issue by ghost** [anchore/scan-action#178]
I've added a [.grype.yaml](https://github.com/BallAerospace/COSMOS/pull/1656/files#diff-d929405c8d1f27de6b8eaa31eab07468a9bc588d8466f23666f329595e8a70ed) file to ignore several issues but it appears that it is being ignored. My latest run is here: https://github.com/BallAerospace/COSMOS/pull/1656/checks?check_run_id=6644500146

I'm scanning a number of containers in a matrix and it appears to all work except for picking up my grype.yaml

**Comment by kzantow** [comment]
Based on the [comment in #226](https://github.com/anchore/scan-action/issues/226#issuecomment-1523687888), I believe this is working properly. I'm going to close this issue for now, but if anyone continues to have issues with this functionality please do reopen it!
