### ISSUE TITLE
Question: scanning unpublished buildah-constructed images as part of workflows?

### ISSUE THREAD

**Issue by jayaddison** [anchore/scan-action#181]
Is it possible to use `anchore/scan-action` (v3) to scan unpublished images that have been built by `buildah` during a GitHub Actions workflow?

(I experimentally attempted to do this in grocy/grocy-docker#173 -- when the pipeline ran, `grype` attempted to pull from a `DockerSource` image source by default, and that [failed](https://github.com/grocy/grocy-docker/runs/7055975411?check_suite_focus=true#step:10:21).  It seems like images must be accessible somehow, since there's an existing [`push-to-registry` step](https://github.com/grocy/grocy-docker/blob/7289344a4943e9633501f2aa727beefb959b3a42/.github/workflows/publish.yml#L43) in the same workflow that is able to read image outputs from [previous job steps](https://github.com/grocy/grocy-docker/blob/7289344a4943e9633501f2aa727beefb959b3a42/.github/workflows/publish.yml#L21-L41).

Please note: I've some vague notions about the differences between OCI and Docker, and I use the `buildah` and `podman` command-line tools a bit locally, but I don't really understand the way that container images are stored, served and retrieved in practice.

**Comment by spiffcs** [comment]
Hey @jayaddison! I saw you had implemented `anchore/scan-action` here:
https://github.com/grocy/grocy-docker/actions/runs/3073563391/jobs/4965778393#step:12:25

Took a brief look at the workflow and saw you had pushed to the registry and then run the scan action and everything was successful.

Today scan-action supports pulling images from registries and directory scans. It does not support scanning a locally built image.

We don't have any current plans to support this, but PRs are definitely welcome!

**Comment by jayaddison** [comment]
Thanks @spiffcs!  Figuring out how to implement local container scanning is a few steps beyond my level of understanding at the moment, but if & when I'm looking into it in future I'll offer any improvements back.

Closing this issue as resolved (you've answered my question).
