### ISSUE TITLE
Error: EACCES: permission denied, open './results.sarif'

### ISSUE THREAD

**Issue by Akash3221** [anchore/scan-action#194]
I am getting this error does anyone know about this error and how to fix it and also "fail-build: false" is not working.

**Comment by kzantow** [comment]
Hi @Akash3221 which version are you using? `@main`?

**Comment by kzantow** [comment]
If you don't need a `sarif` or syft `json` file, with the just released `v3.3.0` you can now use the `output-format: "table"`: https://github.com/anchore/scan-action#action-inputs -- does this meet your use case?

**Comment by shivakumarudutha2312** [comment]
Hi @kzantow output-format: "table" works for me thanks!

**Comment by kzantow** [comment]
Great! Thanks for following up @Akash3221
