### ISSUE TITLE
unable to check for vulnerability database update

### ISSUE THREAD

**Issue by erhan-** [anchore/scan-action#197]
Hey everyone,

I have the following problem at the moment which blocks me for scanning for vulnerabilities:

```
 Executing: grype -o sarif --fail-on medium sbom:action-sandbox-sbom.spdx.json
  [0060] WARN unable to check for vulnerability database update
  
  1 error occurred:
  	* failed to load vulnerability db: vulnerability database is invalid (run db update to correct): database metadata not found: .cache/grype/db/4
  	
```

Does someone have or had this problem as well?

Thanks for your help.

Best regards,

Erhan

**Comment by kzantow** [comment]
Hi @erhan- is this a problem that just started or has it happened for multiple runs? Can you maybe just re-run the workflow to fix it?

This error happens if Grype is unable to download the latest database. I don't see a problem with this happening locally, so the latest database is definitely available and working. Maybe it was a network hiccup on GitHub's side?

**Comment by kzantow** [comment]
One other question: which version are you using? Could you share your action config for this?

**Comment by kzantow** [comment]
Hey @erhan- I'm going to close this one, as I _think_ it was probably just a network hiccup and haven't heard otherwise. Please reopen if this continues to be an issue!

**Comment by erhan-** [comment]
Sorry for not responding. I had not checked my notifications and also have not worked with this for a while. If I get back to this and it does not occur, I will edit this comment as well to confirm the potential network hiccup as well.
Thanks for your help!

**Comment by erhan-** [comment]
@kzantow Hey, I had time to test around again and I can confirm that it is not a connectivity issue. I added a curl step after it to check if the Internet works and it does:

![image](https://user-images.githubusercontent.com/3534714/202464270-8d0c22ca-856d-4271-8aac-d92506ba77f3.png)

We are using Github enterprise. Unfortunately I can not reopen this issue.

**Comment by kzantow** [comment]
> We are using Github enterprise.
> We are using a proxy for the Internet.

Aha! This explains a lot more. I suspect the proxy is not allowing access to the grype db. Can you CURL the latest database from the action?
```
https://toolbox-data.anchore.io/grype/databases/vulnerability-db_v5_2022-10-17T08:14:57Z_b50a86ce07d268101316.tar.gz
```

**Comment by erhan-** [comment]
The env variables are set correctly, also lowercase for both http and https.

Curl works for that file:

![image](https://user-images.githubusercontent.com/3534714/202470836-af84e169-72dd-48dd-97ac-0fec198e493d.png)

**Comment by kzantow** [comment]
Ok, I'm pretty sure I know what the problem is here -- we're providing an environment to the `grype` command: https://github.com/anchore/scan-action/blob/main/index.js#L109

We need to make sure to pass in at least the `HTTPS_PROXY` variable from the existing environment.

This should be a pretty simple thing to get fixed 👍

**Comment by erhan-** [comment]
Good catch!

**Comment by kzantow** [comment]
Thanks for your help on this one @erhan-  -- new release published, so if you're using `anchore/scan-action@v3` you shouldn't have to make any other changes! 👍

**Comment by erhan-** [comment]
No problem. All for security for the people. Are the three dots okay which I commented?

**Comment by kzantow** [comment]
@erhan- I don't know what you mean about "the three dots which I commented"?

**Comment by erhan-** [comment]
I never tried to change anything in node code so this looked strange but I tested and it works:

![grafik](https://user-images.githubusercontent.com/3534714/202653655-436c9619-1daf-4f2e-9fde-b5b337f625ad.png)

Thanks again. All good with 3.3.2

**Comment by kzantow** [comment]
Ahh -- that's the _spread operator_ -- it is used to copy all the properties of an object to another object or all the entries in a list to another list. I did this because I've seen strange things when _modifying_ `process.env`, this way we only modify the `env` object. 👍
