### ISSUE TITLE
Provide a way to have the step passing no matter if the policy returned STOP

### ISSUE THREAD

**Issue by ccamacho** [anchore/scan-action#21]
I'm using anchore as a reporting tool when building my container images and I don't want the action to fail even if there is a policy returning STOP.

Now, providing a policy file with the custom-policy-path parameter I should be able to change the behavior from STOP to WARN in any policy.

Can you provide a .anchore/policy.json example that changes all the policies to WARN, maybe using wildcards? Or if there is another method to have the step always passing would be also ok.

Thanks

**Comment by nightfurys** [comment]
@ccamacho, if you are using Jenkins plugin to scan container images, adding `bailOnFail=false` to the anchore plugin invocation should do the trick. That flag instructs the plugin to not fail the build if the policy evaluation result is stop/fail

**Comment by ccamacho** [comment]
Solution: There is a bug that 'fail-build: false' isn't recognized properly, but if you remove the key completely from the 'with' context then it should work as 'false'.

**Comment by zhill** [comment]
I've added the #22 to track the bug
