### ISSUE TITLE
add support for --add-cpes-if-none

### ISSUE THREAD

**Issue by sebhoss** [anchore/scan-action#215]
I just saw the following log output 

```
  Executing: grype -o sarif --fail-on medium --only-fixed docker.io/metio/devcontainers-terraform@sha256:b7e1848207de8f2e42bae6e33f0f524a1eec416611146c74cf91041478d0a283
  [0013]  WARN some package(s) are missing CPEs. This may result in missing vulnerabilities. You may autogenerate these using: --add-cpes-if-none
```

and was looking for a way to add the --add-cpes-if-none flag but I could not find anything. How about adding another action input to enable/disable this flag?

**Comment by tgerla** [comment]
Hi @sebhoss, thank you for the issue. I think this would be a good feature to add. We'll put this issue in our backlog but please let us know if you are interested in working on this yourself and we can get you started.

**Comment by sebhoss** [comment]
Hey @tgerla, thanks for getting back to me on this! I've created https://github.com/anchore/scan-action/pull/219 which should cover this ^^

**Comment by tgerla** [comment]
That's great, thank you! We will review it as soon as we can.
