### ISSUE TITLE
Configurable `--exclude`

### ISSUE THREAD

**Issue by avorima** [anchore/scan-action#226]
Grype can exclude certain paths from being scanned (https://github.com/anchore/grype#excluding-file-paths) and seeing that ignoring CVEs via `.grype.yaml` hasn't been working for almost a year (https://github.com/anchore/scan-action/issues/178) maybe this is a good compromise.

**Comment by avorima** [comment]
Nevermind, I tried using `.grype.yaml` and it works

**Comment by kzantow** [comment]
Thanks for following up @avorima!
