### ISSUE TITLE
Different results between scan-action and grype run locally

### ISSUE THREAD

**Issue by jacopolanzonidev** [anchore/scan-action#239]
My company uses Grype wrapped by your scan-action to detect vulnerabilities. 

We currently observe a difference between what the scan-action's Grype finds as a GitHub Action and what we get by running Grype locally (installed through brew). 

The version of Grype is the same (v0.63.0)

scan-action:

![Screenshot 2023-08-16 at 17 01 36](https://github.com/anchore/scan-action/assets/121094024/b1d6bbaa-5822-4c00-8e5d-00d8972a7710)

Grype locally:

![Screenshot 2023-08-16 at 17 04 30](https://github.com/anchore/scan-action/assets/121094024/ebedef89-f3c5-4c2c-9a4d-7e10fac7c6a9)

**Comment by jacopolanzonidev** [comment]
Solution found. In my action I wasn't building the project into a jar file, and not all the vulnerabilities are found in that way.

**Comment by tgerla** [comment]
Thanks for letting us know!
