### ISSUE TITLE
grype version of sub action to download grype pinned to 0.63.1

### ISSUE THREAD

**Issue by uli-f** [anchore/scan-action#246]
I use the download grype subaction to download grype and then run it locally (i.e., on the github runner):

```
- name: 💾 Install grype
  uses: anchore/scan-action/download-grype@v3
  id: grype_install

- name: 🕵️ Scan artifact with grype
  run: grype sbom:./build/reports/sbom.json --add-cpes-if-none --config ./grype.yaml --fail-on medium --only-fixed --output template --template grype.sbom.input.template > ./grype-output.txt
```

The downloaded grype version defaults to the pinned version in [GrypeVersion.js](https://github.com/anchore/scan-action/blob/main/GrypeVersion.js). However, this points to a pretty old grype version, that is, 0.63.1.

My understanding is that I can specify the grype version myself in the download subaction. But then I also have to update it manually.

I'd very much appreciate a **feature** where the download subaction always downloads the latest grype release instead of either me (by specifying `grype-version`) or you guys (by specifying a grype version in `GrypeVersion.js`) manually taking care of this.

**Comment by popey** [comment]
This was fixed long ago by #228 it seems?
