### ISSUE TITLE
Seeing runtime errors intermittently 

### ISSUE THREAD

**Issue by Kampe** [anchore/scan-action#25]
Have no issues about 90% of the time, sometimes when the container starts we're presented with this error
```
##[error]The process '/home/runner/work/_actions/anchore/scan-action/master/dist/run_scan.sh' failed with exit code 2
```

**Comment by markyjackson-taulia** [comment]
@Kampe We just released an update to the marketplace [v1.0.3](https://github.com/anchore/scan-action/releases/tag/v1.0.3). Can you give that a go and see if you notice your issue any longer?

**Comment by Kampe** [comment]
Smae issue:
```
Run anchore/scan-action@v1.0.3
/bin/chmod +x /home/runner/work/_temp/d99092e9-0bb8-4969-aafb-29e3c3242799

Analyzing image: XXXXXXXXXXXXXXXX
/home/runner/work/_actions/anchore/scan-action/v1.0.3/dist/run_scan.sh inline_scan docker.io/anchore/inline-scan:v0.7.0 xxxxxxxxxxxxxxxxxxxxxxxxxxx false /home/runner/work/_actions/anchore/scan-action/v1.0.3/dist/critical_security_policy.json critical_security_policy ./Dockerfile
##[error]The process '/home/runner/work/_actions/anchore/scan-action/v1.0.3/dist/run_scan.sh' failed with exit code 2
```

**Comment by markyjackson-taulia** [comment]
Okay, I am debugging

**Comment by markyjackson-taulia** [comment]
@Kampe Can you share your action definition in your `.github/workflow` dir.. Also, can you pass the `debug: true` to the Anchore action so we can get more about your failures?

**Comment by Kampe** [comment]
```
       - name: Scan Container For Vulnerabilities
         uses: anchore/scan-action@v1.0.3
         with:
          image-reference: ${{ env.IMAGE_NAME }}
          dockerfile-path: "./Dockerfile"
          include-app-packages: true
          debug: true
```

**Comment by markyjackson-taulia** [comment]
@Kampe What image are you scanning, or that base image?

**Comment by Kampe** [comment]
I'm scanning my own image that was created in the step before.

**Comment by markyjackson-taulia** [comment]
What is the base of that image? Also, Can you give the output of the run with the debug?
If it makes it easier, we can jump on a zoom too.

**Comment by Kampe** [comment]
Yeah sorry on a walk right now so only have my phone, we use this step across all of our repositories after we build our container before we push it to our registry. I'll post the debug content here on a second.

**Comment by derekjanni** [comment]
Since Nick's afk and I'm also having problems with this
[anchore_logs.txt](https://github.com/anchore/scan-action/files/4424212/anchore_logs.txt)

**Comment by markyjackson-taulia** [comment]
@derekjanni I see `2020-04-02T22:53:45.9627880Z [MainThread] [anchore_manager.cli.analyzers/exec()] [ERROR] Error: Failed to unpack image (gcr.io/edf-re/esap_billing@sha256:0a97ccb2868e3c54167317fe7a2fc58e5123290d6c5b653a725091cbf18ca1ea) - exception: [Errno 28] No space left on device`

**Comment by Kampe** [comment]
Is this a limitation of Github Actions then?

**Comment by markyjackson-taulia** [comment]
Yeah. You can see [here](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions) for more info on that

**Comment by markyjackson-taulia** [comment]
@Kampe @derekjanni 

Is there anything else I can help with here?
