### ISSUE TITLE
Adding support for `--vex`

### ISSUE THREAD

**Issue by ferozsalam** [anchore/scan-action#253]
Hi, I'd be keen to add support for the `--vex` [option](https://github.com/anchore/grype#vex-support) that has recently been added to Grype. Is there interest in this feature being added? If so, I'm happy to open a PR for this.

**Comment by tgerla** [comment]
Hey @ferozsalam, that sounds great, please go ahead! We would be happy to review a PR. Thanks.

**Comment by spiffcs** [comment]
Closing this issue since #254 was merged! Thanks for the PR @ferozsalam
