### ISSUE TITLE
Update the actions runtime to Node.js 20

### ISSUE THREAD

**Issue by peter-murray** [anchore/scan-action#276]
GitHub Actions is currently generating warnings about updating the action to Node.js 20, which needs to be set in the `actions.yml` file.

See here for more details: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by cxMiguelSilva** [comment]
I am having the same problem. The action is flagging itself.

**Comment by stevehipwell** [comment]
It looks like this issue could be closed if a new release was cut?

**Comment by spiffcs** [comment]
Thanks for the bump @stevehipwell - I'll try and get a new release cut this week

**Comment by kzantow** [comment]
This was done in https://github.com/anchore/scan-action/pull/278
