### ISSUE TITLE
Enable the support on Anchore enterprise

### ISSUE THREAD

**Issue by cafeliker** [anchore/scan-action#29]
The Readme said "The action invokes the inline version of anchore engine, which is a script and docker image that run completely locally and scan a local docker image and return the content, policy evaluation, and a final pass/fail status for the image."

Do you plan to enable the support on Anchore enterprise? In enterprise, the policy needs to be centrally controlled in the Anchore enterprise, can it be downloaded before the local scan runs?

Thanks
ye

**Comment by markyjackson-taulia** [comment]
We can definitely take a look at that!

**Comment by kzantow** [comment]
I'm closing this issue as it is no longer pertinent -- this action is a wrapper for Grype, and as such does not integrate with Anchore enterprise.
