### ISSUE TITLE
Scan action fails decode syft-json document

### ISSUE THREAD

**Issue by hkadakia** [anchore/scan-action#298]
Seeing the below issue when running scan-action
```
Run anchore/sbom-action@9fece9e20048ca9590af301449208b2b8861333b
  with:
    image: nginx:latest
    format: syft-json
    output-file: /tmp/sbom.syft.json

Run anchore/scan-action@3343887d815d7b07465f6fdcd395bd66508d486a
  with:
    fail-build: false
    sbom: /tmp/sbom.syft.json
    output-format: json

Executing: grype -o json --fail-on medium sbom:/tmp/sbom.syft.json
  1 error occurred:
  	* failed to catalog: unable to decode sbom: unable to decode syft-json document: json: cannot unmarshal object into Go struct field Document.artifacts of type string
 ```

Syft/Sbom-action version: 9fece9e20048ca9590af301449208b2b8861333b (v0.15.9)
Grype/Scan-action version: 3343887d815d7b07465f6fdcd395bd66508d486a (v3.6.4)

**Comment by popey** [comment]
Hi @hkadakia - thanks so much for filing this issue. Apologies for the delay getting back to you.
We have some confidence that this _should_ be resolved in a newer release, but some more testing is required. Are you still seeing this behavior with the latest releases of sbom-action and scan-action?

**Comment by popey** [comment]
Hi @hkadakia - I'm going to close this issue, feel free to re-open or start a new one if this is an issue with the currently released version.

**Comment by hkadakia** [comment]
Yes I haven't noticed any issues so far.
