### ISSUE TITLE
Problem running scan-action

### ISSUE THREAD

**Issue by nuno-seco** [anchore/scan-action#41]
I started seeing the following error in our automated scanning. 
Notice the typo in `descrption`.

I am not completely familiar with the our setup but I dont believe this is reltated to anything we have done on our side. Is there anyone else experiencing the same? 

```
Download action repository 'anchore/scan-action@v1.0.2'
##[error]anchore/scan-action/v1.0.2/action.yml (Line: 33, Col: 5): Unexpected value 'descrption'
##[error]anchore/scan-action/v1.0.2/action.yml (Line: 33, Col: 5): Unexpected value 'descrption'
##[error]Fail to load anchore/scan-action/v1.0.2/action.yml```

**Comment by triffer** [comment]
This is already fixed in newer versions, so you can just update the version of the action. I think GitHub activated some validation, that's why this error shows up.

**Comment by nuno-seco** [comment]
Yes. it works fine in the latest version.
