### ISSUE TITLE
Breaking changes, release notes and changelog

### ISSUE THREAD

**Issue by NicolasCARPi** [anchore/scan-action#56]
Hello,

After release of v2 my scans were failing. Turns out that one needs to use `image` instead of `image-reference`. This is a breaking change that should be mentioned in the release notes.

Also, this repository is missing a `CHANGELOG.md` file. I suggest adding one. It's quite handy to follow the changes.

Best,
~Nico

**Comment by zhill** [comment]
@NicolasCARPi thanks, and we'll make changes clearer in the future including a changelog.
