### ISSUE TITLE
debug:false still shows Debug output

### ISSUE THREAD

**Issue by mendhak** [anchore/scan-action#77]
Hello there, I tried to use the [debug Action Input](https://github.com/anchore/scan-action#action-inputs), but I noticed that if I set `debug: false` the DEBUG output is still appearing in the logs.  If I remove the debug key, or set it to 'false' in quotes, same problem.   

I've created a sample repo to show this problem.  [See the log output here](https://github.com/mendhak/anchore-scan-debug-false/runs/1581631340?check_suite_focus=true#step:3:44), and here [I am setting debug: false](https://github.com/mendhak/anchore-scan-debug-false/blob/main/.github/workflows/blank.yml#L31-L33). 

Apologies if I've misunderstood the purpose of `debug: false`.  

Some screenshots

![image](https://user-images.githubusercontent.com/746276/102691166-737ef500-4202-11eb-92f4-71a80643f311.png)

![image](https://user-images.githubusercontent.com/746276/102691172-809be400-4202-11eb-94ba-65afb03fc3ad.png)

**Comment by alfredodeza** [comment]
Hi @mendhak , thanks for reporting this, you are spot on. There is a mismatch on how the debug flag is passed on to `grype` which is the underlying tool that does the matching.
