### ISSUE TITLE
brutal amount of debug information and JSON metadata

### ISSUE THREAD

**Issue by alfredodeza** [anchore/scan-action#87]
Regardless of the verbosity level (now correctly captured by https://github.com/anchore/scan-action/issues/77) the amount of output is overwhelming, amounting to noise rather than being useful - even on situations where `debug: false`. 

This happens because the `@actions/exec` call defaults to sending all output to the log. This option would be fine to enable with `debug: true`, but cumbersome to always be on.

The `exec` call offers controls over the output. For reference, here is the interface:

```js
export interface ExecOptions {
  /** optional working directory.  defaults to current */
  cwd?: string

  /** optional envvar dictionary.  defaults to current process's env */
  env?: {[key: string]: string}

  /** optional.  defaults to false */
  silent?: boolean

  /** optional out stream to use. Defaults to process.stdout */
  outStream?: stream.Writable

  /** optional err stream to use. Defaults to process.stderr */
  errStream?: stream.Writable

  /** optional. whether to skip quoting/escaping arguments if needed.  defaults to false. */
  windowsVerbatimArguments?: boolean

  /** optional.  whether to fail if output to stderr.  defaults to false */
  failOnStdErr?: boolean

  /** optional.  defaults to failing on non zero.  ignore will not fail leaving it up to the caller */
  ignoreReturnCode?: boolean

  /** optional. How long in ms to wait for STDIO streams to close after the exit event of the process before terminating. defaults to 10000 */
  delay?: number

  /** optional. Listeners for output. Callback functions that will be called on these events */
  listeners?: {
    stdout?: (data: Buffer) => void

    stderr?: (data: Buffer) => void

    stdline?: (data: string) => void

    errline?: (data: string) => void

    debug?: (data: string) => void
  }
}
```

And this is the example on how to control the output that could be applied in the action:

```js
let myOutput = '';
let myError = '';

const options = {};
options.listeners = {
  stdout: (data: Buffer) => {
    myOutput += data.toString();
  },
  stderr: (data: Buffer) => {
    myError += data.toString();
  }
};
options.cwd = './lib';

await exec.exec('node', ['index.js', 'foo=bar'], options);
```

Another point worth noting is that the current tests use `stderr` output as a means to verify correctness. `grype` does great at sending JSON to `stdout` for easier redirection, so it makes it easier to just capture `stderr` for vulnerability matching.

The problem is that if the build fails with vulnerabilities being found and `debug: false` the output is not meaningful:

```
 grype --fail-on=medium -o json python:3.8 > out.log
 ✔ Vulnerability DB     [no update available]
 ✔ Loaded image
 ✔ Parsed image
 ✔ Cataloged image      [436 packages]
 ✔ Scanned image        [1567 vulnerabilities]

discovered vulnerabilities at or above the severity threshold
```

Since SARIF reporting is still in BETA, this type of workflow wouldn't be helpful. It would be ideal to be able to have some sort of minimal reporting done as well when failures are hit - regardless of what `grype` is capturing. 

So if this change makes it in, the test jobs will need to enable debug

**Comment by kzantow** [comment]
This has been addressed and also Grype STDERR output is grouped into a collapsed-by-default section, like this:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/3009477/160461736-763213ba-2d25-4d82-ba7a-b962b9604722.png">
