### ISSUE TITLE
Improve SARIF report

### ISSUE THREAD

**Issue by alfredodeza** [anchore/scan-action#90]
Some improvements are needed in the SARIF report which is currently not very friendly:

* Make the title as human readable as possible and explain what the vulnerability is. Something like `netty-codec-http2: Possible request smuggling in HTTP/2` gives folks a better idea of what the problem is. 
 
* Use the help content to provide rich details about the vulnerability and the impact. This should be narrative content which describes the problem you've discovered, and includes text from the underlying CVE.

* For the alert location, tag the file in the repository, not the file on the container image. This is especially important if we're talking about a repo with many Dockerfiles. If you want to add additional content about the file in the container image, maybe do that by providing multiple locations (which would show up in the `show paths` dialog)

**Comment by emosbaugh** [comment]
It is impossible to tell which image is being referenced for vulnerabilities in the SARIF report. In my case I am scanning many public images and there is no Dockerfile. This is similar to the last bullet point.

![Screen Shot 2021-03-25 at 8 51 25 PM](https://user-images.githubusercontent.com/371319/112637519-7db12080-8dfb-11eb-8ac2-3ccc5c7cb17b.png)
