### ISSUE TITLE
False positive on Github Actions results for "critical" cut-off

### ISSUE THREAD

**Issue by wagnerpereira** [anchore/scan-action#93]
**Running Scanner local doesn't show any critical issues:**

➜ $ grype version
Application:          grype
Version:              0.9.0
BuildDate:            2021-03-26T12:16:56Z
GitCommit:            7ce9ef647ed415334920538fdaeb451876e52f4c
GitTreeState:         clean
Platform:             darwin/amd64
GoVersion:            go1.14.15
Compiler:             gc
Supported DB Schema:  1

➜  $ grype --fail-on critical image:5a03002936db6a4759890fc8cc267497c3cfea69
 ✔ Vulnerability DB     [no update available]
 ✔ Loaded image
 ✔ Parsed image
 ✔ Cataloged image      [624 packages]
 ✔ Scanned image        [495 vulnerabilities]
➜ $ echo $?
0

**Running on Github Actions:**

Run anchore/scan-action@v2
./anchore-reports/content.json
/usr/bin/chmod +x /home/runner/work/_temp/b2ab22ff-74fe-4a27-aaa0-948a0a4f293e
/home/runner/work/_temp/b2ab22ff-74fe-4a27-aaa0-948a0a4f293e -b /home/runner/work/_temp/b2ab22ff-74fe-4a27-aaa0-948a0a4f293e_grype v0.7.0
anchore/grype info checking GitHub for tag 'v0.7.0'
anchore/grype info found version: 0.7.0 for v0.7.0/linux/amd64
anchore/grype info installed /home/runner/work/_temp/b2ab22ff-74fe-4a27-aaa0-948a0a4f293e_grype/grype

Analyzing: image:5a03002936db6a4759890fc8cc267497c3cfea69
/opt/hostedtoolcache/grype/0.7.0/x64/grype -vv -o json --fail-on critical image:5a03002936db6a4759890fc8cc267497c3cfea69
[0000] DEBUG Application config:
configpath: ""
presenteropt: 1
output: json
scopeopt: Squashed
scope: Squashed
quiet: false
log:
  structured: false
  levelopt: debug
  level: ""
  filelocation: ""
clioptions:
  configpath: ""
  verbosity: 2
db:
  dir: /home/runner/.cache/grype/db
  updateurl: https://toolbox-data.anchore.io/grype/databases/listing.json
  autoupdate: true
  validatebyhashonstart: false
dev:
  profilecpu: false
checkforappupdate: true
failon: critical
failonseverity: 5

[0000]  INFO New version of grype is available: 0.9.0

...
lot of log output later
...

discovered vulnerabilities at or above the severity threshold
Error: Failed minimum severity level. Found vulnerabilities with level critical or higher

**Can't reproduce and find any error running grype locally on my mac**

Thank you for any help, would love to use it on my pipeline.

**Comment by alfredodeza** [comment]
Hi @wagnerpereira ! Thanks for taking the time to report this. I believe this is because there is a mismatch in the grype versions. You have 0.9.0 and the action is using 0.7.0

Can you switch over to 0.7.0 locally and see if you get the difference? I'll cut a new release soon to bump grype to the latest

**Comment by wagnerpereira** [comment]
Great!! It was exactly that.

  - name: Scan image for critical vulnerabilities
    uses: anchore/scan-action@v2
    with:
      grype-version: 0.9.0
      image: "image:tag"
      fail-build: true
      severity-cutoff: "critical"

Now it is working! I'll try to send ACS report to github.

Wonderful! It will be great if we could remove all the log output. Just a summary of the execution.

Thanks!
